### PR TITLE
Move daemons/gptp as separate repo under AVnu

### PR DESCRIPTION
**Pull request by avinash-palleti**
Removing daemons/gptp folder from OpenAVnu and updated all build files and
travis-ci files.

### CODE REVIEW

**Comment by andrew-elder** [comment]
This looks ok to me. Does anyone have any comments? @avinash-palleti - I assume build instructions have also been updated. There are a few to many changes for me to review in details.

**Comment by avinash-palleti** [comment]
> What about these instructions https://github.com/AVnu/OpenAvnu/tree/master/lib/avtp_pipeline ?

This still holds good as we have not modified anything in avtp_pipeline.

**Comment by andrew-elder** [comment]
avtp_pipeline depends on gptp (for example). How will it build?

**Comment by avinash-palleti** [comment]
It is building, i just now verified `make avtp_pipeline`

**Comment by andrew-elder** [comment]
If I don't see any further comments, I'm going to merge this pull request tomorrow morning.

**Pull request merged**
