### PR TITLE
MAAP bug-fixes and improvements

### PR DESCRIPTION
**Pull request by pinealservo**
I've rebased the internal development work we've done on the MAAP daemon to the open-avb-next branch. This is a very large set of patches, since it encompasses development done over a long period of time, but it only touches files within the maap subdirectory and some top-level build files.

The branch can be browsed here, where you can also see the nicely-rendered documentation in the new README: https://github.com/pinealservo/Open-AVB/tree/maap_staging/daemons/maap

The code includes unit tests, which are integrated with the Travis build and successfully pass.

### CODE REVIEW

**Comment by andrew-elder** [comment]
Thank you for submitting this @pinealservo and @bdthomsen ! It looks excellent.

**Comment by pinealservo** [comment]
I just did a pass to make the formatting more consistent across all the maap files and with the OpenAvnu repository in general.

I should also note that the remote interface to the maap daemon is different now; the old one wasn't capable of supporting full MAAP functionality. Anything that was talking to the old one will need to be updated.

**Comment by andrew-elder** [comment]
I'm ok with approving this commit as is. I need one more person to sign off on it.

**Comment by bdthomsen** [comment]
I approve as well, with the caveat that as one of the authors of the code, I can't claim to be impartial.

**Comment by andrew-elder** [comment]
No one else had any comments, so I'm going to go ahead an merge this.

**Pull request merged**
