### PR TITLE
Feature avtp pipeline avdecc

### PR DESCRIPTION
**Pull request by andrew-elder**
A rather large pull request to merge AVDECC capability on to the AVTP pipeline code.

### CODE REVIEW

**Comment by andrew-elder** [comment]
Anyone else have comments on this? I in favor of merging it.

**Comment by pinealservo** [comment]
I am in favor of merging it too, although I wish there was someone else who was interested in the avtp_pipeline code that would take a look. I have looked through all of Brant's changes in local code reviews and we've been testing it in a few of our configurations (PC + i210 as well as a couple of ARM-based boards) with a couple of different controllers.

**Comment by andrew-elder** [comment]
I'll wait another 24 hours to see if anyone else has any further comments, otherwise I'll go ahead and merge.

**Comment by bdthomsen** [comment]
Thanks Andrew.  Just to clarify, the branch will still remain active, as we are continuing to add features and fix issues as they are discovered.  However, future pull requests to open-avb-next should be much smaller than this one.

**Pull request merged**
