### PR TITLE
Remove lib/igb and kmod/igb folder as part of restructuring

### PR DESCRIPTION
**Pull request by avinash-palleti**
Removed lib/igb and kmod/igb and created as separate repos under AVnu.
lib/igb is again added as submodule to lib/igb_avb/lib as there is build
dependency for lib/common.

### CODE REVIEW

**Comment by feishengfei** [comment]
It seems that new travis.sh script should be involved in pull request

**Comment by avinash-palleti** [comment]
> It seems that new travis.sh script should be involved in pull request

I updated travis.sh file in this PR.

**Comment by avinash-palleti** [comment]
@andrew-elder . Done, i updated commit hash for lib/igb_avb submodule and CI is passing.

**Comment by andrew-elder** [comment]
Great. If I don't see any further comments, I will merge this pull request later today.

**Comment by avinash-palleti** [comment]
@andrew-elder If there are no comments on this PR, can you please merge. 
I will submit another one for daemons/gptp

**Pull request merged**
