### PR TITLE
fix building on Xcode 10

### PR DESCRIPTION
**Pull request by lhoward**
Fix warnings/build errors on Xcode 10

### CODE REVIEW

**Comment by andrew-elder** [comment]
Thanks @lhoward . All the change look good. Do you mind redoing the pull request against open-avb-next. We us that branch as a staging branch before merging to master. Thanks!

**Comment by lhoward** [comment]
@andrew-elder done

**Comment by andrew-elder** [comment]
Sorry, I wasn't clear. I meant to say that your pull request should also be made to open-avb-next, not master. Thanks.

**Comment by lhoward** [comment]
I just changed the base in Github, is that OK?

**Comment by andrew-elder** [comment]
Looks fine to me. Thank you for the updated request. I need one other person to approve the pull request.

**Pull request merged**
