### PR TITLE
Aquantia NIC support

### PR DESCRIPTION
**Pull request by Egor-Pomozov-AQ**
- Add atl_avb submodule
- Update Makefiles, .cmake and CMakeList.txt to support a building of Aquantia hardware support
- Add atl lib support to common lib 
- Add atl_simple_talker example
- Add asyncronous storing to pcap  file in example applications
- Add send_packet_precisely example application
- Add run_atl.sh file to simple installation of atl_tsn driver
- Add atl hardware support in avtp_pipeline:
    - Create new atl_rawsock
    - Create new scheme of launchtime calculation
    - Add support for non-compressed audio streams
    - Update logging system to support a log from hardware library
- Apply fix in mrp_client.c

### CODE REVIEW

**Comment by Egor-Pomozov-AQ** [comment]
Fix building issues in atl lib

**Comment by andrew-elder** [comment]
@Egor-Pomozov-AQ - thank you for this pull request!
Do you mind re-submitting it against branch open-avb-next? Merging and testing through the open-avb-next branch is the preferred integration path.

**Comment by Egor-Pomozov-AQ** [comment]
Hello Andrew,

Okay. We’ll retest our solution with this branch.

--
Best Regards,
Egor Pomozov
epomozov@marvell.com<mailto:epomozov@marvell.com>

**Comment by Egor-Pomozov-AQ** [comment]
It will be reopened to merge in 'open-avb-next' branch.

**Pull request closed without merging**
