### PR TITLE
gPTP: Windows: MSVC compile fixes

### PR DESCRIPTION
**Pull request by andrew-elder**

### CODE REVIEW

**Comment by andrew-elder** [comment]
@christopher-s-hall - is this what you were thinking?

**Comment by christopher-s-hall** [comment]
Yes on the code, but I think we should keep the Intel PCH controller PHY delays. The actual PHY delay is difficult to pin down on these devices and usually involves experimentation, but those numbers are "pretty close" for any recent Intel platforms.

**Comment by andrew-elder** [comment]
I copied the delays from the linux build. I noticed the change when updating the #defines. Are the PCH delays different than I210 ones? And are you saying we should default to the non-I210 ones? So that would mean I would revert the #define names for the windows build?

**Comment by christopher-s-hall** [comment]
The PHY delays are different on the PCH. Please use the PCH ones for the Windows build unless we have an I210 driver for Windows.

**Comment by andrew-elder** [comment]
@christopher-s-hall - changes incorporated. Please confirm this is what you were thinking.

**Comment by christopher-s-hall** [comment]
Looks good to me.

**Comment by andrew-elder** [comment]
@bdthomsen - can you please take a minute to review (and hopefully merge). Then I can submit my next pull request!

**Comment by zeefpt** [comment]
Hi folks can you please review my issues ?

https://github.com/AVnu/OpenAvnu/issues/622
https://github.com/AVnu/OpenAvnu/issues/619
Im really stucked.

Best Regards ;

**Pull request merged**
